name: "PR Subtree Push"

permissions:
  contents: write

on:
  push:
    branches:
        - main
jobs:
  sync-subtrees:
    runs-on: macos-26
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      
      - name: Subtree - LiveRamp
        uses: ./.github/actions/subtree-split-push
        with:
          subtree: extensions/LiveRamp
          remote: gh-liveramp
          target-branch: main
          token: ${{ secrets.NIMBUS_PAT }}